### ISSUE TITLE
Error when generating proxy classes

### ISSUE THREAD

**Issue by michaelcerne** [codingjungle/toolbox#12]
I get this error about halfway through generating proxy classes:
```
ParseError thrown with message "syntax error, unexpected 'if' (T_IF), expecting identifier (T_STRING) or '{'"

Stacktrace:
#15 ParseError in {root}/httpdocs/init.php:820
#14 IPS\IPS:monkeyPatch in {root}/httpdocs/init.php:797
#13 IPS\IPS:autoloader in [internal]:0
#12 spl_autoload_call in [internal]:0
#11 property_exists in {root}/httpdocs/applications/toolbox/sources/Proxy/Generator/Proxy.php:240
#10 IPS\toolbox\Proxy\Generator\_Proxy:create in {root}/httpdocs/applications/toolbox/sources/Proxy/Proxyclass/Proxyclass.php:307
#9 IPS\toolbox\Proxy\_Proxyclass:build in {root}/httpdocs/applications/toolbox/sources/Proxy/Proxyclass/Proxyclass.php:205
#8 IPS\toolbox\Proxy\_Proxyclass:run in {root}/httpdocs/applications/toolbox/modules/admin/proxy/proxy.php:67
#7 IPS\toolbox\modules\admin\proxy\_proxy:IPS\toolbox\modules\admin\proxy\{closure} in {root}/httpdocs/system/Helpers/MultipleRedirect/MultipleRedirect.php:92
#6 IPS\Helpers\_MultipleRedirect:__construct in {root}/httpdocs/init.php:820
#5 IPS\Helpers\toolbox_hook_MultiRedirect:__construct in {root}/httpdocs/applications/toolbox/modules/admin/proxy/proxy.php:132
#4 IPS\toolbox\modules\admin\proxy\_proxy:manage in {root}/httpdocs/system/Dispatcher/Controller.php:96
#3 IPS\Dispatcher\_Controller:execute in {root}/httpdocs/applications/toolbox/modules/admin/proxy/proxy.php:45
#2 IPS\toolbox\modules\admin\proxy\_proxy:execute in {root}/httpdocs/system/Dispatcher/Dispatcher.php:152
#1 IPS\_Dispatcher:run in {root}/httpdocs/init.php:820
#0 IPS\toolbox_hook_Dispatcher:run in {root}/httpdocs/admin/index.php:14
```
Any ideas what might be causing this? Looks like something in `init.php` isn't being parsed correctly, but it's a stock install.

**Comment by codingjungle** [comment]
it doesn't appear to be a problem with proxyclass generator, it appears to be whatever file it is processing when it is hitting this.

`if (property_exists( $dbClass, 'databaseTable' ) && class_exists($dbClass) && method_exists($dbClass, 'db'))`

the error is being thrown by whatever class property_exists is loading to check for a property. #12 of the back trace shows it autoloading the class, then it failing. unfortunately its not showing what file its trying to load, it could be a hook or a class to a 3rd party app (to test, i ran it on a full suite for 4.4 and 4.5 and this error didn't happen to either one).

**Comment by michaelcerne** [comment]
Any ideas for how I could debug that for you? I could probably have it write out each class as it loads.

**Comment by codingjungle** [comment]
if you switch to the 4.5 branch (it is tweaks that have been made to toolbox for 4.5, but it works as for 4.4.x as well as most of the changes for 4.5 are cosmetic when it comes to the toolbox).

i've added a catch for ParseErrors, it will add it to the ips system logs if you have DEBUG_LOG set to true in your constants.php (or if you use the toolbox's profiler and have debug+ajax debug enabled it will put the error there). they will have have the type of 'ParseErrorFile' (ParseError is the actual error, ProxyClass type are generalized things that might need fixed, but not always).

but there really isn't anything for me to debug, as the error is in the file it is trying to process, not with proxyclass generator, i've put a catch in there so the proxyclass can complete.

**Comment by Satariall** [comment]
Hi @codingjungle . I'm on 4.5 branch try to generate proxy classes. They didn't work and only returns popup 'foo' message after refreshing page on click 'save' event. There someting 'in progress' state, is it?)

**Comment by codingjungle** [comment]
[](url)
![2020-06-26_19-13](https://user-images.githubusercontent.com/3393297/85910058-7ca68080-b7e2-11ea-8c32-082f4a27948a.png)
![2020-06-26_19-21](https://user-images.githubusercontent.com/3393297/85910060-7d3f1700-b7e2-11ea-860e-d5bd42b157d9.png)

if you don't use the profiler with debug enabled, it will use the ips log, you can follow the images above to find where that is located to find the error (note: in these images i simulated an error in one of the files for toolbox, so this error isn't actually present when parsing for proxyclass).

**Comment by codingjungle** [comment]
> Hi @codingjungle . I'm on 4.5 branch try to generate proxy classes. They didn't work and only returns popup 'foo' message after refreshing page on click 'save' event. There someting 'in progress' state, is it?)
> upd. I proceed to the uri https://localhost/admin/?app=toolbox&module=proxy&controller=proxy and proxy classes generates well

not sure, sounds like you have a bit more going on that a problem with proxyclass,  the only one that pops up with a "foo" is when you save settings, proxyclass will say 'Proxy Classes have been Generated'.

**Comment by michaelcerne** [comment]
Thanks @codingjungle, appreciate it. I'm gonna close this and try that out.
