### ISSUE TITLE
Error while creating proxy classes

### ISSUE THREAD

**Issue by Hepi420** [codingjungle/toolbox#19]
On a fresh install with only the toolbox app on 4.5.3 I get this error while trying to generate proxy classes.

"Class 'IPS\nexus\Invoice\Item\Purchase' not found"

![image](https://user-images.githubusercontent.com/5824853/95926259-83262b80-0dc4-11eb-8da9-d401a42f46ca.png)

**Comment by codingjungle** [comment]
this really isn't a bug. you don't have nexus, two ways to fix this for your use case, either remove any of the /extension/nexus folders for the apps that have these extensions or open up toolbox/sources/Proxy/Proxyclass/Proxyclass.php and find the method 'excludeDir()' and the path 'extensions/nexus' to the returned array or you can how that class and do it that way.

**Comment by royysz** [comment]
Adding extensions/nexus to the array fixed the problem, thanks for the fast response,
I dont have any 3rd party applications installed so I dont know where this error came from, I just installed 4.5.3 with your toolbox app and tried to create the proxy classes.

**Comment by codingjungle** [comment]
>I dont have any 3rd party applications installed so I dont know where this error came from, I just installed 4.5.3 with your toolbox app and tried to create the proxy classes.

Nexus (Commerce) is an IPS app, and their other apps use the nexus extensions, but they are only loaded by nexus. so if you don't have it installed, the extensions can be there without issue, but proxyclass grabs all the php and phtml files (with the exception of those in the excludeDir/excludeFiles methods) and processes them with no regard what is and isn't installed or enabled.
