### ISSUE TITLE
After generating the proxy classes the end redirect triggers a CSRF IPS error

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#31]
**Describe the bug**
After generating the proxy classes the end redirect triggers a CSRF IPS error because the link includes an unneeded call to the csrf() function.

**To Reproduce**
1. Simply run the tool to generate proxy classes and wait for it to end

**Expected behavior**
It should redirect to ACP dashboard without error.

**Additional context**
I fixed it by replacing the code below in "\applications\toolbox\modules\admin\proxy\proxy.php" on line 138:
`$url = Url::internal('app=core&module=overview&controller=dashboard')->csrf();`

with:
`$url = Url::internal('app=core&module=overview&controller=dashboard');`

**Comment by codingjungle** [comment]
you must be on an older version, cause  it shouldn't lead to the MR any longer, it should be kicking off an ajax call :)

**Comment by terabyte-gc** [comment]
I'm on the latest files from the DEV branch?

**Comment by terabyte-gc** [comment]
Hmm, I am indeed on the latest commit from the DEV branch, but the file I have locally doesn't match what's in the repo. Weird. I'll try cloning the repo again.
