### ISSUE TITLE
Any way to make the Proxy Class Generator tool skip certain folders?

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#32]
**Is your feature request related to a problem? Please describe.**
I have a **_nodeploy** folder in my root IPS folder that contains several old css files, themes, cms pages, etc. that I keep for tracking changes and other things. When I run the Proxy Class Generator tool it also picks up all the files in that folder and throws errors because they are not properly formatted like a normal/proper IPS file.

**Describe the solution you'd like**
Either make tool search only inside the default IPS folders (admin, applications, dev, etc.) or maybe add a setting to exclude specific folders by path/name?

**Describe alternatives you've considered**
It took me quite a while to track down what the issue was since, at first, I thought it was a new bug with the 4.6 version that wasn't fixed yet. For now the simple solution I've come up with is to temporarily move the **_nodeploy** folder outside of where the IPS suite files are, run the tool, and then move back the folder. While I don't run the tool that often, it's still an annoying step.

**Comment by codingjungle** [comment]
yes in toolbox/sources/Proxy/Proxyclass/Proxyclass.php, go to method "excludeDir" (currently on line 641 of the latest), and you can add the folder name or the relative path, and the generator should skip that directory.  you can also do the same thing for files, in the excludedFiles method for files.

**Comment by codingjungle** [comment]
in the latest commit, if in your IPS root directory (where conf_global.php can be found) if you added a file called "excluded.php" and include 2 arrays like this:
`<?php
$excludeFolders = [
    'Foo'
];

$excludeFiles = [
    'Foo.php'
];`

proxyclass generator will check if this file exists, include it and merge the results with excludeDirs and excludeFiles methods in proxyclass.
