### ISSUE TITLE
"...try again". Is that like a joke?

### ISSUE THREAD

**Issue by Hatead1** [codingjungle/toolbox#33]
Error when try to work with marketplace application
'Something has gone wrong try again!'
from sources/DevFolder/Applications.php

**Expected behavior**
Normal message "This application is from the IPS marketplace and cannot be processed." or like that.

**Comment by codingjungle** [comment]
not really a joke. the toolbox is missing polish in some places.

**Comment by codingjungle** [comment]
changed in the latest commit on the dev branch.
