### ISSUE TITLE
Duplicate content in "dev" files

### ISSUE THREAD

**Issue by Hatead1** [codingjungle/toolbox#35]
**Describe the bug**
Duplicate content in css, templates, resources (in images). 

**To Reproduce**
1. Run Application Dev Folder Generator in any mode several times in a row.

**Expected behavior**
Clear dev folder content before generate (with confirm message).

**Comment by codingjungle** [comment]
this is expected behavior, as it should be you the dev going in and making sure the dev folder isn't there or to clean it out on your own.

**Comment by Hatead1** [comment]
"expected behavior" - does this now mean "i'm lazy to add verification and cleanup and will not even warn you of possible problems with duplicated content (yep, images too!)"? 

You do not want to at least add a warning that dev folder already exists and the contents of the files will be incorrect?

**Comment by codingjungle** [comment]
> "expected behavior" - does this now mean "i'm lazy to add verification and cleanup and will not even warn you of possible problems with duplicated content (yep, images too!)"?

well the expected behavior is that it generates a dev folder, its not entire meant to wipe out and/or replace an existing dev folder and it isn't unreasonable imho for you to check first. 

> 
> You do not want to at least add a warning that dev folder already exists and the contents of the files will be incorrect?

feel free to add what you want to this section, and do a pull request and i will take a look at it, and merge it if acceptable.

**Comment by Hatead1** [comment]
> generates a dev folder
correct dev-folder, no?

I'm not programmer, sorry. I just added
        $this->dev = $this->dir . '/dev/';
        if(file_exists($this-dev)) {
            throw new Exception('Dev folder exists, remove it before processing.');
        }
аnd my problem is solved.
