### ISSUE TITLE
Application export/download will break any classes which contain "hook" in the filename

### ISSUE THREAD

**Issue by DanielFatkic** [codingjungle/toolbox#36]
**Describe the bug**
It seems that there's some logic to add "//" to any php file which contains hook in the name ( for example "webhook" ) which is going to break the script.

 
**To Reproduce**
1. Create a controller call "hook manager" in a custom application
2. Export the application and install it on a test board 
4. Open the  controller => it's going to result in a white page.

**Additional context**

If you open the created controller, you'll notice that the code begins with 
`//<?php`

instead of
`<?php`

**Comment by codingjungle** [comment]
I'll remove this section of the code, as it is no longer needed. i use git hooks now for similar functionality.
