### ISSUE TITLE
DevFolder for plugins missing or removed? 

### ISSUE THREAD

**Issue by Hatead1** [codingjungle/toolbox#38]
Only Application.php in sources/DevFolder/
Copied from master branch, everything works fine.

**Comment by codingjungle** [comment]
This feature was removed quite awhile ago, as the functionality is now "native" in IPS while IN_DEV is enabled. 

I've removed the multiredirect hook that was the last lingering bit of it (as i don't create plugins myself, so i didn't notice this was still there).
