### ISSUE TITLE
Patching init.php or Helpers triggers a CSRF IPS error

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#39]
**Describe the bug**
After patching init.php or Helpers the end redirect triggers a CSRF IPS error because the link includes an unneeded call to the csrf() function.

**To Reproduce**
1. Simply run either patch tool

**Expected behavior**
It should redirect to the settings page without error. 😋

**Additional context**
I fixed it by replacing the lines below in "\applications\toolbox\modules\admin\settings\settings.php":
```
Output::i()->redirect($this->url->csrf(), 'init.php patched with Debug Helpers');

Output::i()->redirect($this->url->csrf(), 'init.php patched');
```

with:
```
Output::i()->redirect($this->url, 'init.php patched with Debug Helpers');

Output::i()->redirect($this->url, 'init.php patched');
```

**Comment by codingjungle** [comment]
I'm actually gonna remove the "patch helpers" as i moved those to the constance.php awhile back. I'll leave the code there incase anyone wants to use it, but i prefer it in the constants.php.

this will be fixed on the next update.
