### ISSUE TITLE
Patching Helpers after init.php results in an error

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#40]
**Describe the bug**
Patching first init.php and then the Helpers results in an error because the Helpers code gets added twice.

**To Reproduce**
1. Run the init.php patch tool
2. Run the Helpers patch tool
3. After the redirect you'll see an error

**Expected behavior**
It should redirect to the settings page without error. 😋

**Additional context**
This happens because of the latest change on how init.php is patched. Since the new code adds an IPSBU class extension the replace code for the Helpers tool does the replace twice because it matches both **class IPS** and **class IPSBU**
`$content = str_replace('class IPS', $r, $content);`

**Comment by codingjungle** [comment]
yeah, i should've removed it, as i no longer use it. they get added to the constants.php if you set the constants from toolbox. 

i've commented out the link for it, but left the code that alters things in place.
