### ISSUE TITLE
Proxy Class Generator tool duplicates some CSS files

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#41]
**Describe the bug**
Proxy Class Generator tool generates a duplicate copy of the CSS files of all applications + HTML Purifier 3rd party tool.

**To Reproduce**
1. Simply run the tool to generate proxy classes and wait for it to end
2. Check the **\dtProxy** folder and you'll find a duplicate of the mentioned CSS files inside **\dtProxy\css\dtProxy**

**Expected behavior**
The folder is in the default excluded directories list but the tool doesn't seem to be taking it into account at all. 😋

**Comment by codingjungle** [comment]
fixed
