### ISSUE TITLE
Rebuild IN_DEV folder for already installed plugins

### ISSUE THREAD

**Issue by terabyte-gc** [codingjungle/toolbox#43]
**Is your feature request related to a problem? Please describe.**
The IN_DEV folder for plugins is created on install, but I'm not seeing any option to rebuild it for already installed plugins (like for the apps with "Generate Application Dev Folder"). If you don't have the XML file to re-install the plugin it's impossible to rebuild it.

**Describe the solution you'd like**
An option similar to the apps: **Generate Plugin Dev Folder**.

**Additional context**
Recently I needed to modify a custom plugin for someone, they didn't have the XML file anymore (yeah, I know... lol) but thankfully they had a development board with it installed. I figured I could rebuild the IN_DEV files installing the toolbox app but then I hit the problem above. 😋

In the end I managed but having the option to also rebuild already installed plugins would have been nice and easier.

**Comment by codingjungle** [comment]
I took the original plugin dev folders cause IPS does it now (i think daniel added it in), as for rebuilding it without the xml might be difficult, as i don't think it stores everything with in the plugin folder or in the DB if it is install in a live install, i'll see what i can do, but can't make any promises.
