### ISSUE TITLE
opache_reset error

### ISSUE THREAD

**Issue by reficul** [codingjungle/toolbox#5]
Every times I switch from or to in_dev:

`Error: Call to undefined function opcache_reset() (0)
#0 /Users/sviluppo/Documents/sites/440.test/applications/toolbox/sources/Build/Cons.php(114): IPS\toolbox\Build\_Cons->save(Array, Array)
#1 /Users/sviluppo/Documents/sites/440.test/applications/toolbox/modules/admin/settings/cons.php(40): IPS\toolbox\Build\_Cons->form()
#2 /Users/sviluppo/Documents/sites/440.test/system/Dispatcher/Controller.php(96): IPS\toolbox\modules\admin\settings\_cons->manage()
#3 /Users/sviluppo/Documents/sites/440.test/applications/toolbox/modules/admin/settings/cons.php(32): IPS\Dispatcher\_Controller->execute()
#4 /Users/sviluppo/Documents/sites/440.test/system/Dispatcher/Dispatcher.php(152): IPS\toolbox\modules\admin\settings\_cons->execute()
#5 /Users/sviluppo/Documents/sites/440.test/admin/index.php(14): IPS\_Dispatcher->run()
#6 {main}`

**Comment by codingjungle** [comment]
The fix is in the xp branch along with other improvements

**Comment by codingjungle** [comment]
Sorry they are in the dev branch
