### ISSUE TITLE
Class not found when generate proxy class

### ISSUE THREAD

**Issue by fogmoon** [codingjungle/toolbox#9]
Hi,

I use your dev branch to add `Dev Toolbox` application. When I click the menu `Proxy Class Generator`, the progress just freeze on half and show char `b` under the progress bar. 

![image](https://user-images.githubusercontent.com/22490781/61960968-2987e480-aff9-11e9-9838-9ec910075561.png)

I check the chrome network panel and find the exception:

```
Whoops\Exception\ErrorException: Class 'IPS\nexus\Invoice\Item\Purchase' not found in file /www/forum/applications/core/extensions/nexus/Item/ClubMembership.php on line 24
Stack trace:
  1. Whoops\Exception\ErrorException->() /www/forum/applications/core/extensions/nexus/Item/ClubMembership.php:24
```

I think this exception arise maybe relative to I did not purchase the `Commerce` app.  FYI, I also did not purchase `Gallery` and `Download` app, which I think purchase later.

Could you please check that?

Thanks very much.

**Comment by codingjungle** [comment]
a fix been pushed to the dev branch.

**Comment by fogmoon** [comment]
Great, it works now. Thanks so much.

A very very small bug, your popup menu have two `Proxy Class Generator` item.
